version: '3.8'

services:
  # Сервис для Django бэкенда
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - db_data:/app/
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    restart: unless-stopped

  # Сервис для Nginx
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
  static_volume:
  media_volume: