FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY backend/requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY backend /app

EXPOSE 8000
CMD ["gunicorn", "velo_api.wsgi:application", "--bind", "0.0.0.0:8000"]