# Generated by Django 5.2.1 on 2025-05-29 00:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('brand_name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('brand_brief_description', models.CharField(blank=True, max_length=256, verbose_name='Краткое описание')),
                ('brand_full_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='ArchivedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('detailes', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_coef', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(through='shop.ProductInstance', to='shop.product'),
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('model_name', models.CharField(max_length=64, verbose_name='Модель')),
                ('brief_description', models.CharField(max_length=256, verbose_name='Краткое описание')),
                ('type', models.CharField(choices=[('L', 'Детский'), ('I', 'Взрослый')], max_length=1, verbose_name='Тип велосипеда')),
                ('wheel_size', models.IntegerField(verbose_name='Диаметр колеса (inch.)')),
                ('frame_size', models.IntegerField(verbose_name='Размер рамы (inch.)')),
                ('characteristics_detailed', models.JSONField(verbose_name='Дополнительные характеристики')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.brand', verbose_name='Бренд')),
            ],
            options={
                'abstract': False,
            },
            bases=('shop.product',),
        ),
    ]
