# Generated by Django 5.2.1 on 2025-06-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_cart_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedcart',
            options={'verbose_name': 'Архивированная корзина', 'verbose_name_plural': 'Архивированные корзины'},
        ),
        migrations.AlterModelOptions(
            name='bicycle',
            options={'verbose_name': 'Велосипед', 'verbose_name_plural': 'Велосипеды'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='productinstance',
            options={'verbose_name': 'Экземпляр продукта', 'verbose_name_plural': 'Экземпляры продуктов'},
        ),
    ]
