# Generated by Django 5.2.2 on 2025-06-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_archivedcart_options_alter_bicycle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='characteristics_detailed',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительные характеристики'),
        ),
    ]
