# Generated by Django 5.2.2 on 2025-06-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_image_alter_bicycle_characteristics_detailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_in_stock',
            field=models.IntegerField(default=0, verbose_name='Количество на складе'),
        ),
    ]
